language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install numpy
  - pip install pandas

script:
  - python test_User.py
  - python test_calculation.py
  - python test_bankingDS.py
  - python test_bankingUI.py