language: python
python:
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install numpy
  - pip install pandas
  - pip install html5lib
  - pip install matplotlib

script:
  - python test_User.py
  - python test_calculation.py
  - python test_bankingDS.py
  - python test_bankingUI.py